#!/bin/bash

# Repeat given char N times using shell function
repeat(){
	local start=1
	local end=${1:-80}
	local str="${2:-=}"
	local range=$(seq $start $end)
	for i in $range ; do echo -n "${str}"; done
}

org_volume=`amixer -D pulse get Master|tail -n1|sed -E 's/.*\[([0-9]+)\%\].*/\1/'`
i=1

notify-send "Volume" -t 500 -i notification-audio-volume-medium -h int:value:$volume
#repeat 20 "/"

volume=$((org_volume / 5))
volume_bar=""

while (( $i <= $volume ));
do
	volume_bar="${volume_bar}]"
	i=$i+1
done
i=$((20-$volume))
while (( $i > 0 ));
do
	volume_bar="${volume_bar}-"

	i=$i-1

done

echo "${volume_bar}${org_volume}"
